#This file was originally generated by PyScripter's unit test wizard

import unittest
from ibeams import IBeam, IBeamK, IBeamSortament

class TestIBeam(unittest.TestCase):

    def setUp(self):
        s = IBeamSortament()
        s.findbyname("16")
        self.ib = IBeam(s.getIBeamParams())

    def tearDown(self):
        pass

    def testmassa(self):
        self.assertEqual(self.ib.massa, 15.9)

    def testget_mass_by_len(self):
        self.assertEqual(self.ib.get_mass_by_len(2) , 31.8)

    def testget_len_by_mass(self):
        self.assertEqual(self.ib.get_len_by_mass(31.8) , 2)

    def testget_paint_area(self):
        self.assertEqual(self.ib.get_paint_area(1) , 0.603)

    def testget_free_length(self):
        self.assertEqual(self.ib.get_free_length() , 17*150)

    def testJz(self):
        self.assertEqual(self.ib.Jz, 58.6)

    def testiz(self):
        self.assertEqual(self.ib.iz, 1.7)

class TestIBeamK(unittest.TestCase):

    def setUp(self):
        s = IBeamSortament()
        s.findbyname("20")
        self.ib = IBeamK(s.getIBeamParams())

    def tearDown(self):
        pass

    def testmassa(self):
        self.assertEqual(self.ib.massa, 42)

    def testJy(self):
        self.assertEqual(self.ib.Jy, 3680)

    def testJz(self):
        self.assertAlmostEqual(self.ib.Jz, 1570, delta=5)

    def testget_mass_by_len(self):
        self.assertEqual(self.ib.get_mass_by_len(1) , 42)

    def testget_len_by_mass(self):
        self.assertEqual(self.ib.get_len_by_mass(84) , 2)

    def testget_paint_area(self):
        self.assertEqual(float(self.ib.params_row["parea"]), 0.75)
        self.assertEqual(float(self.ib.params_row["b"]), 100)
        self.assertEqual(self.ib.get_paint_area(1) , 0.95)

    def testget_free_length(self):
        self.assertAlmostEqual(self.ib.get_free_length(), 8115, delta=5)

if __name__ == '__main__':
    unittest.main(TestIBeamK())
